- set_fact:
    dir_bin     : "{{ django_prefix }}/bin"
  when: "django_prefix != ''"

- set_fact:
    dir_bin     : ""
  when: "django_prefix == ''"

- include: "bin.yml"

#
# Install conda requirements
#

- stat:
    path: "{{ dir_etc }}/requirements-conda.txt"
  register: "st"

- name: "conda: (conda) requirements file from template"
  template:
    src: "requirements-conda.txt"
    dest: "{{ dir_etc }}/requirements-conda.txt"
  when: "st.stat.exists == True"

- name: "conda: install conda requirements"
  command: "{{ conda }} install --file {{ dir_etc }}/requirements-conda.txt{% if conda_channel %} -c {{ conda_channel }}{% endif %} -y -q --json"
  register: "__aux"
  when: "st.stat.exists == True"


#
# Install pip requirements
#
- name: "conda: (pip) requirements file from template"
  template:
    src: "requirements.txt"
    dest: "{{ dir_etc }}/requirements.txt"

- name: "conda: install pip requirements"
  pip:
    chdir: "{{ django_root }}"
    requirements: "{{ dir_etc }}/requirements.txt"
    executable: "{{ pip }}"
