#
# Pull, and find out instance name
#

- include: "root.yml"
- include: "name.yml"
- include: "pull.yml"
  when: django_pull|bool

#
# Action
#

- include: "domains.yml"
- include: "dirs.yml"

- include: "pip.yml"
  when: "python_env == 'pip'"
- include: "conda.yml"
  when: "python_env == 'conda'"

- include: "settings.yml"
- include: "manage.yml"
- include: "database.yml"

#
# uwsgi, nginx, monit
#
- include: "uwsgi.yml"

- include: "static.yml"
  when: django_with_nginx|bool

- include: "nginx.yml"
  when: django_with_nginx|bool

- include: "monit.yml"
  when: django_with_monit|bool
