#
# Certbot
#
- name: "Certbot dirs"
  file:
    path: "{{ dir_www }}/.well-known/acme-challenge"
    state: "directory"
  when: "django_https"

- name: "Certbot ping file (for testing only)"
  copy:
    dest: "{{ dir_www }}/.well-known/acme-challenge/ping"
    content: "pong"
  when: "django_https"

- name: "Certbot configuration"
  template:
    src: "certbot.conf"
    dest: "{{ dir_etc }}/certbot.conf"
  when: "django_https"

#
# HTTPS or HTTP
#

- name: "Certificate's full path"
  set_fact:
    certificate: "/etc/letsencrypt/live/{{ django_domain }}/fullchain.pem"
  when: "django_https"

- name: "Certificate is there or not"
  stat:
    path: "{{ certificate }}"
  register: "st"
  when: "django_https"

- name: "Certificate not there, then make it empty"
  set_fact:
    certificate: ""
  when: "django_https and st.stat.exists == False"

#
# Nginx
#

- name: "Nginx configuration"
  template:
    src: "nginx.conf"
    dest: "{{ dir_etc }}/nginx.conf"
  notify: "reload nginx"

- name: "(sudo) Nginx: mkdir /etc/nginx/sites"
  file: "path=/etc/nginx/sites state=directory"
  become: true
  when: "django_with_sudo"

- name: "Nginx symlink"
  file:
    path: "/etc/nginx/sites/{{ name }}.conf"
    state: "link"
    src: "{{ dir_etc }}/nginx.conf"
  notify: "reload nginx"
  become: true
  when: "django_with_sudo"
