#
# Setup virtual environment
#
# Input : django_root
# Output: dir_venv
# Requires:
#

# Requirements as a template
- name: "pip: requirements file from template"
  template:
    src: "requirements.txt"
    dest: "{{ dir_etc }}/requirements.txt"

- name: "pip: dir_venv"
  set_fact:
    dir_venv: "{{ django_root }}/venv"

# Internal variables
- which:
    name: "python{{ python_version }}"
    dest: "python"

# Action
- name: "pip: create venv and install requirements"
  pip:
    chdir: "{{ django_root }}"
    requirements: "{{ dir_etc }}/requirements.txt"
    virtualenv: "{{ dir_venv }}"
    virtualenv_python: "{{ python if python_version == '2.7' else omit }}"
    virtualenv_command: "{{ python + ' -m venv' if python_version != '2.7' else omit }}"

- name: "pip: update path to Python"
  set_fact:
    python: "{{ dir_venv }}/bin/python"
