#
# Setup virtual environment
#
# Input : django_root
# Output: dir_venv
# Requires:
#

# venv directory defined here, because conda expects it not to be set
- set_fact:
    dir_venv    : "{{ django_root }}/venv{{ python_version_short }}"

- set_fact:
    dir_bin     : "{{ dir_venv }}/bin"

- include: "bin.yml"

# Requirements as a template
- name: "pip: requirements file from template"
  template:
    src: "requirements.txt"
    dest: "{{ dir_etc }}/requirements.txt"

# Internal variables
- which:
    name: "python{{ python_version }}"
    dest: "python_sys"

# Action
- name: "pip: create venv and install requirements"
  pip:
    chdir: "{{ django_root }}"
    requirements: "{{ dir_etc }}/requirements.txt"
    virtualenv: "{{ dir_venv }}"
    virtualenv_command: "{{ python_sys + ' -m venv' }}"
