#
# Uwsgi configuration
#
# Input : dir_etc, dir_run
# Output: file_sock, file_fifo, file_pid
# Requires:
#

- name: "Paths to uwsgi files"
  set_fact:
    file_sock: "{{ dir_run }}/uwsgi.socket"
    file_fifo: "{{ dir_run }}/uwsgi.fifo"
    file_pid : "{{ dir_run }}/uwsgi.pid"

- name: "Check uwsgi is running (1/2)"
  stat:
    path: "{{ file_pid }}"
  register: "__aux"

- name: "Check uwsgi is running (2/2)"
  set_fact:
    uwsgi_running: "{{ __aux.stat.exists }}"

- name: "Uwsgi configuration"
  template:
    src: "uwsgi.ini"
    dest: "{{ dir_etc }}/uwsgi.ini"
  notify: "reload uwsgi"

- name: "Start/Stop scripts"
  template:
    src: "{{ item }}"
    dest: "{{ dir_etc }}/{{ item }}"
    mode: "0744"
  with_items:
  - "start.sh"
  - "stop.sh"
