#
# Setup virtual environment
#
# Input : django_root, python_venv
# Output: dir_venv
# Requires:
#

- set_fact:
    dir_venv: "{{ django_root }}/usr"
  when: "python_venv != ''"

# Requirements as a template
- name: "Requirements file from template"
  template:
    src: "requirements.txt"
    dest: "{{ dir_etc }}/requirements.txt"

# Internal variables
- name: "Find out path to Python binary"
  command: "which python{{ python_version }}"
  register: "__aux"
  changed_when: false

- set_fact:
    python: "{{ __aux.stdout }}"

- name: "Find out path to pip"
  command: "which pip"
  register: "__aux"
  changed_when: false

- set_fact:
    pip: "{{ __aux.stdout }}"

# Action, with or without venv
- name: "Virtualenv & pip"
  pip:
    virtualenv: "{{ dir_venv }}"
    virtualenv_python: "{{ python }}"
    virtualenv_command: "{{ python_venv }}"
    requirements: "{{ dir_etc }}/requirements.txt"
  when: "python_venv != ''"

- name: "Update path to Python"
  set_fact:
    python: "{{ dir_venv }}/bin/python"
  when: "python_venv != ''"

- name: "(Just) Pip"
  pip:
    executable: "{{ pip }}"
    requirements: "{{ dir_etc }}/requirements.txt"
  when: "python_venv == ''"
