- name: "reload uwsgi"
  shell: "echo r > {{ file_fifo }}"
  when: "uwsgi_running"

- name: "reload nginx"
  service: "name=nginx state=reloaded"
  become: true
  when: django_with_sudo|bool

- name: "restart monit"
  service: "name=monit state=restarted"
  become: true
  when: django_with_sudo|bool
